### ISSUE TITLE
Stencil: Cannot find module '@nrwl/workspace/src/utilities/ast-utils'

### ISSUE THREAD

**Issue by nathan2slime** [nxext/nx-extensions#939] opened 2023-05-08 19:59 UTC
**Describe the bug**

When trying to generate a stencil library, it returns the following error

```shell
Cannot find module '@nrwl/workspace/src/utilities/ast-utils'
```

**To Reproduce**

1. Create a base monorepo using nx
```shell
yarn create nx-workspace app
```

2. Add the manager as specified in the documentation in the installation step

```
yarn add @nxext/stencil -D
```

3. Try to generate a stencil library as specified in the documentation

```
yarn nx g @nxext/stencil:library core
```
**Expected behavior**
It should generate a stencil component library

**Additional context**
If it is a compatibility issue with nx versions, please specify which dependencies are compatible, below is my package.json

> package.json

```json
{
  "name": "example",
  "version": "0.0.0",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "@nrwl/workspace": "^16.1.2",
    "nx": "16.1.2",
    "nx-cloud": "latest",
    "typescript": "^5.0.4"
  },
  "workspaces": [
    "packages/*"
  ],
  "dependencies": {
    "@nxext/stencil": "^15.7.0"
  }
}
```

> Logs

![Captura de tela 2023-05-08 165214](https://user-images.githubusercontent.com/105957472/236920273-73629a2f-15db-48b1-95fc-c9c4f7d5e251.png)

**Comment by matsgottenbos** [comment] 2023-05-24 10:50
This seems like a duplicate of #922.
See my comment there for a pretty simple workaround: https://github.com/nxext/nx-extensions/issues/922#issuecomment-1560895150

**Closed** 2023-07-16 19:28 UTC
Labels: bug
